### ISSUE TITLE
Incosistency between Makefile and docs

### ISSUE THREAD

**Issue by idoqo** [networkop/k8s-networking-guide#1]
I recently started playing around with k8s and decided to give the lab a spin. [The lab doc](https://k8s.networkop.co.uk/lab/#interacting-with-the-lab) asks to run `make stop` followed by `make destroy` to free up the resources but none of those rules exist. 

There're `down` and `cleanup` rules in the Makefile though, which seems like the right commands to use. I could send in a fix PR to the main repo if my assumptions are right.

**Comment by networkop** [comment]
yes, please do!

**Comment by networkop** [comment]
fixed in #2. thanks @idoqo for a quick fix.
