### ISSUE TITLE
kindnet diagram has wrong ip addressing

### ISSUE THREAD

**Issue by hellt** [networkop/k8s-networking-guide#19]
Hi @networkop 
here https://www.tkng.io/cni/kindnet/ you have typos in node addressing (3rd octets) and some static addresses as well

**Comment by networkop** [comment]
thanks for reporting @hellt , I'll double check it later this week.

**Comment by networkop** [comment]
@hellt how does it look now?

**Comment by hellt** [comment]
sometimes there are caching issues with drawio
I still see it the same
![image](https://user-images.githubusercontent.com/5679861/132093026-81808e6f-bf8e-49b7-836c-ddde1f213f4d.png)

**Comment by networkop** [comment]
this looks like an updated version. what issue are you seeing @hellt ?

**Comment by hellt** [comment]
I thought worker should have .1 in 3rd octet and worker two should have had
.2

**Comment by networkop** [comment]
I think it should be good now. Can you confirm @hellt ?

**Comment by hellt** [comment]
now its all good
thanks
