### ISSUE TITLE
ipvs: broken link

### ISSUE THREAD

**Issue by gmichelo** [networkop/k8s-networking-guide#27]
Hi! Great content first of all!

The link here is broken:
https://github.com/networkop/k8s-networking-guide/blob/master/content/services/clusterIP/dataplane/IPVS.md?plain=1#L280

I guess it can be replaces with either [this SlideShare](https://www.slideshare.net/LCChina/scale-kubernetes-to-support-50000-services) or [this GitHub](https://github.com/sbueringer/kubecon-slides/blob/master/slides/2017-kubecon-eu/Scale%20Kubernetes%20to%20Support%2050%2C000%20Services%20%5BI%5D%20-%20Haibin%20Xie%20%26%20Quinton%20Hoole%2C%20Huawei%20Technologies%20-%20Scale%20Kubernetes%20to%20Support%2050000%20Services.pdf).

**Comment by networkop** [comment]
fixed in [e743239](https://github.com/networkop/k8s-networking-guide/commit/e7432390c1b41759901594cf16e7d80ee5c1c9a4)
thanks for reporting @gmichelo
