### ISSUE TITLE
Confusion in diagram notations.

### ISSUE THREAD

**Issue by Vyom-Yadav** [networkop/k8s-networking-guide#31]
Sorry, super dump question. I probably know the answer to this, but I will still ask 'cause my networking knowledge is not super good.

![Screenshot from 2023-06-13 23-00-01](https://github.com/networkop/k8s-networking-guide/assets/73882557/cf3724cb-d6a5-4bc3-a188-478ec0a1d0cd)
![Screenshot from 2023-06-13 22-59-48](https://github.com/networkop/k8s-networking-guide/assets/73882557/c752bd29-2bdb-492d-9f0d-7b4cfd15556c)

What does **L2** and **L3** exactly specify in the above diagram? I know it link and network layer respectively. But what do they exactly specify? 

Like in the first image, L3 specifies that flow from `cbr0` -> `flannel.1` is layer 3 routing and L2 specifies that `flannel.1` internally does layer 2 routing (by adding internal MAC address and VXLAN header + UDP headers + outer IP header). Also then why does, `flannel.1` -> `eth0`.4 does not have that L3 tag? 

Bit confusing.

In the second image, like does it mean packets from `vethX` -> `eth0`.11 are routed using L3? This notation is pretty obvious but I want to still clarify whether I am thinking right or wrong.

Sorry for this question and really awesome work on this project, helps a lot!!

**Comment by Vyom-Yadav** [comment]
@networkop Sorry for pinging but can you please clarify? :)

**Comment by networkop** [comment]
L3 and L2 are supposed to represent IP and MAC address lookup respectively. The result of a L3 lookup should be a next-hop IP address, and the result of a L2 lookup should be the egress port.
The two arrows around it is a common icon for a switch, e.g. https://static.thenounproject.com/png/56982-200.png (representing an "device" where these lookups happen)

So L3 and L2 do not represent a link but rather a forwarding engine (kernel routing table for L3, bridging table for L2). This is why the L3 for eth0 is drawn under the `kind` bridge, which is where the forwarding lookup for happens. Although, strictly speaking, the `kind` bridge only performs a L2 lookup but this is just an implementation detail as, in general, this can be a L3 network.
