### ISSUE TITLE
pre-req installer script

### ISSUE THREAD

**Issue by hellt** [networkop/k8s-networking-guide#5]
Hi Michael,
for those who create on-demand/clean VM for tkng lab cluster it might be quite compelling to have an installer script that installs the prerequisite components.

For this purpose I created a simple bash script that installs latest stable versions of docker-ce, kubectl, helm and make for Ubuntu 20.4 LTS AMD64.

https://gist.github.com/hellt/61242c680c78c3c813f20ecb9577a93e

Feel free to consider if its worth adding a link to it to the docs

ADD1: later I will update it to have extras installed as well (k9s, auto-completions, etc)

**Comment by networkop** [comment]
Thanks, this is very helpful. I've added a reference to it in adc48e12b3f1c9e85b5114a68fd9666ffc293f2e
